package com.zhongyang.java.dao;

import java.util.List;

import com.zhongyang.java.zyfyback.pojo.SysAuthorization;

public interface SysAuthorizationMapper {
	
	List<SysAuthorization> selectAll();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SYS_AUTHORIZATION
     *
     * @mbggenerated
     */
    void deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SYS_AUTHORIZATION
     *
     * @mbggenerated
     */
    int insert(SysAuthorization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SYS_AUTHORIZATION
     *
     * @mbggenerated
     */
    int insertSelective(SysAuthorization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SYS_AUTHORIZATION
     *
     * @mbggenerated
     */
    SysAuthorization selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SYS_AUTHORIZATION
     *
     * @mbggenerated
     */
    void updateByPrimaryKeySelective(SysAuthorization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SYS_AUTHORIZATION
     *
     * @mbggenerated
     */
    void updateByPrimaryKey(SysAuthorization record);
}